### ISSUE TITLE
It should be written in Markdown

### ISSUE THREAD

**Issue by karlgroves** [karlgroves/a11y-lawsuits#1]
The list should be written in Markdown, not HTML, for greatest portability.  Then, pandoc can be used to convert the output

**Comment by jpdevries** [comment]
Big fan of pandoc. I just took a whack at a Jekyll to site + EPUB workflow. Couldn't get any of the Jekyll plugins to work but came up with a workflow where I use Gulp to process the Markdown files to prep them for pandoc, then feed that to pandoc and create and run the bash command to run pandoc. Works great!

**Comment by mgifford** [comment]
Wow..  Hadn't run into [pandoc](http://pandoc.org/) before. Sweet.

$ brew install pandoc
$ pandoc lawsuits.html -t markdown -f html -s -o lawsuits.md.txt

[lawsuits.md.txt](https://github.com/karlgroves/a11y-lawsuits/files/814129/lawsuits.md.txt)

**Comment by karlgroves** [comment]
Closing

As of right now I'm using CSV as single source of truth and has much greater portability and maintainability.
