### ISSUE TITLE
Unprintable character in lawsuits.csv

### ISSUE THREAD

**Issue by carmacleod** [karlgroves/a11y-lawsuits#20]
The "Greyhound Lines and Firstgroup Americaæ" entry in the csv file has an `æ` character that shows up as a question mark within a black diamond in the browser (Windows/Chrome):

![snapshot of strange-looking character in lawsuits table](https://user-images.githubusercontent.com/3331913/32288958-cef90b1e-bf0b-11e7-8364-c435b141de90.png)

**Comment by karlgroves** [comment]
Thanks!
