### ISSUE TITLE
NBA & ABC

### ISSUE THREAD

**Issue by mgifford** [karlgroves/a11y-lawsuits#5]
I should just for the repo, but...
http://www.thelegalintelligencer.com/id=1202741984905/NBA-Sued-by-Blind-Man-Over-Website-

http://www.theguardian.com/media/2015/jul/07/blind-woman-sues-abc-for-discrimination-over-lack-of-audio-narration

**Comment by karlgroves** [comment]
Added NBA to latest update.
ABC not added as my list is focused on web-based technologies.  I'd like to eventually turn this into more of a database with a lot more data but for now, anything other than web is beyond what I can afford time for.
