### ISSUE TITLE
Higher Ed Accessibility Lawsuits, Complaints, and Settlements

### ISSUE THREAD

**Issue by mgifford** [karlgroves/a11y-lawsuits#6]
Link to Laura L. Carlson's list?
http://www.d.umn.edu/~lcarlson/atteam/lawsuits.html

**Comment by karlgroves** [comment]
Thanks for the recommendation.  Added several from her list and from Terrill Thompson's list in my latest update, as the Dept. of Ed OCR doesn't publish their settlements in an easy-to-consume list the way DOJ does.

**Comment by mgifford** [comment]
Hey, thanks for setting up this collaborative effort..

**Comment by jpdevries** [comment]
I'm working on some related research. Does anyone know if any coding bootcamps have been targeted yet?
