### ISSUE TITLE
table header columns are off

### ISSUE THREAD

**Issue by tnguyen14** [karlgroves/a11y-lawsuits#9]
<img width="858" alt="screen shot 2016-01-08 at 3 21 31 pm" src="https://cloud.githubusercontent.com/assets/1652595/12208566/8d29ac02-b61b-11e5-9f27-a9935c52f832.png">

**Comment by karlgroves** [comment]
This issue is related to my blog post and not the code. I think that the blog post has been fixed, but it has also def. been fixed in this code

See: http://karlgroves.github.io/a11y-lawsuits/lawsuits.html
